apiVersion: v1
kind: Service
metadata:
  name: k8s-101
  labels:
    app: k8s-101
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: k8s-101
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-102
  labels:
    app: k8s-102
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: k8s-102
